site_name: BT and the Planeteers
site_url: https://zkbt.github.com/team
nav:
    - Welcome: index.md
    - Basics: 
      - Who?: basics/who.md
      - What?: basics/what.md
      - Why?: basics/why.md
      - Where?: basics/where.md
      - When?: basics/when.md
      - How?: basics/how.md
    - Details: 
      - Computing: details/computing.md
      - Reading: details/reading.md
      - Writing: details/writing.md
      - Visualizing: details/visualizing.md
      - Proposing: details/proposing.md
      - Collaborating: details/collaborating.md
    - references.md
theme:
  name: "material"
  features:
      - navigation.tracking
repo_url: https://github.com/zkbt/team/
plugins:
  - search
  - mkdocs-jupyter:
      execute : True
      include_source : True
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../team]
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: True
            show_root_heading: True
            show_root_toc_entry: False
            show_root_full_path: False
            show_category_heading: False
            show_submodules: False
            merge_init_into_class: False
            show_if_no_docstring: False
            heading_level: 3
            show_bases: False
  - exclude:
      glob:     
        - "*.pdf"
        - "*.fits"
        - "*.npy"
        - "*.ecsv"
markdown_extensions:
    - toc:
        permalink: "#"

# this is super borrowed from Christina Hedges' fabulous
# https://christinahedges.github.io/astronomy_workflow/
